### ISSUE TITLE
Installing PyGFSV2

### ISSUE THREAD

**Issue by ghost** [retostauffer/PyGFSV2#1]
I believe this will be an elementary question but after using `pip` to install the necessary libraries that are used with PyGFSV2, is there a pip command to install PyGFSV2?  I am looking for how to download this library, and while I may have a fundemental misunderstanding, I was not successful.  Thank you for your help.

**Comment by retostauffer** [comment]
Dear @rivers31334 
Thank's for your request. I've changed the repository structure such that you should now be able to install the library using `pip`. Extended the README file which now contains some installation instructions. Tested on a fresh python2.7 installation on my machine and seems to work as it should now. If there are any further issues please let me know!

Greez
R
