### ISSUE TITLE
error code 1 at installation

### ISSUE THREAD

**Issue by myusernameisunique** [retostauffer/PyGFSV2#2]
i got this:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kn9fezqj/logging/

when i ran this:
pip install git+https://github.com/retostauffer/PyGFSV2.git

is there a fix?

**Comment by retostauffer** [comment]
Dear Sir or Madam

Thank you for your question. I've double-checked the installation on my system and I cannot reproduce your error.

The error you have more looks like a problem with the logging package.

May you try:

* [sudo] pip install --upgrade --force-reinstall logging
* [sudo] pip install git+https://github.com/retostauffer/PyGFSV2.git

.. and, if not working, send me the output from pip?

All best,
R

**Comment by myusernameisunique** [comment]
adding sudo worked for installation.
thank you.

**Comment by retostauffer** [comment]
Welcome!
